[2025-04-11T19:53:02.755+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rag_daily_discovery.run_discovery_flow manual__2025-04-11T19:52:59.316322+00:00 [queued]>
[2025-04-11T19:53:02.763+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rag_daily_discovery.run_discovery_flow manual__2025-04-11T19:52:59.316322+00:00 [queued]>
[2025-04-11T19:53:02.763+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-04-11T19:53:02.774+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_discovery_flow> on 2025-04-11 19:52:59.316322+00:00
[2025-04-11T19:53:02.788+0000] {standard_task_runner.py:60} INFO - Started process 188 to run task
[2025-04-11T19:53:02.790+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'rag_daily_discovery', 'run_discovery_flow', 'manual__2025-04-11T19:52:59.316322+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/rag_daily_discovery.py', '--cfg-path', '/tmp/tmpk7k099bu']
[2025-04-11T19:53:02.791+0000] {standard_task_runner.py:88} INFO - Job 166: Subtask run_discovery_flow
[2025-04-11T19:53:02.831+0000] {task_command.py:423} INFO - Running <TaskInstance: rag_daily_discovery.run_discovery_flow manual__2025-04-11T19:52:59.316322+00:00 [running]> on host e8e823252435
[2025-04-11T19:53:02.871+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rag_daily_discovery' AIRFLOW_CTX_TASK_ID='run_discovery_flow' AIRFLOW_CTX_EXECUTION_DATE='2025-04-11T19:52:59.316322+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-11T19:52:59.316322+00:00'
[2025-04-11T19:53:08.457+0000] {logging_mixin.py:188} INFO - üîç Searching for: Sure! Here‚Äôs a list of artists and songs known for strong isolated percussion or vocal sections ideal for sampling:
[2025-04-11T19:53:08.560+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rag_daily_discovery.py", line 16, in discovery_flow
    results_df = search_many(queries)
  File "/opt/airflow/backend/rag_pipeline/search_youtube.py", line 45, in search_many
    vids = search_youtube(query, max_results=max_results)
  File "/opt/airflow/backend/rag_pipeline/search_youtube.py", line 23, in search_youtube
    res.raise_for_status()
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.googleapis.com/youtube/v3/search?part=snippet&q=Sure%21+Here%E2%80%99s+a+list+of+artists+and+songs+known+for+strong+isolated+percussion+or+vocal+sections+ideal+for+sampling%3A&type=video&videoEmbeddable=true&maxResults=3
[2025-04-11T19:53:08.571+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=rag_daily_discovery, task_id=run_discovery_flow, execution_date=20250411T195259, start_date=20250411T195302, end_date=20250411T195308
[2025-04-11T19:53:08.580+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 166 for task run_discovery_flow (403 Client Error: Forbidden for url: https://www.googleapis.com/youtube/v3/search?part=snippet&q=Sure%21+Here%E2%80%99s+a+list+of+artists+and+songs+known+for+strong+isolated+percussion+or+vocal+sections+ideal+for+sampling%3A&type=video&videoEmbeddable=true&maxResults=3; 188)
[2025-04-11T19:53:08.612+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-11T19:53:08.626+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
