[2025-04-10T17:39:02.887+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: isoloops_ingest.convert_csv_to_parquet manual__2025-04-10T17:39:01.527746+00:00 [queued]>
[2025-04-10T17:39:02.891+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: isoloops_ingest.convert_csv_to_parquet manual__2025-04-10T17:39:01.527746+00:00 [queued]>
[2025-04-10T17:39:02.891+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-04-10T17:39:02.898+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): convert_csv_to_parquet> on 2025-04-10 17:39:01.527746+00:00
[2025-04-10T17:39:02.906+0000] {standard_task_runner.py:60} INFO - Started process 72 to run task
[2025-04-10T17:39:02.910+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'isoloops_ingest', 'convert_csv_to_parquet', 'manual__2025-04-10T17:39:01.527746+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/isoloops_ingest.py', '--cfg-path', '/tmp/tmplfz9uxkf']
[2025-04-10T17:39:02.912+0000] {standard_task_runner.py:88} INFO - Job 92: Subtask convert_csv_to_parquet
[2025-04-10T17:39:02.942+0000] {task_command.py:423} INFO - Running <TaskInstance: isoloops_ingest.convert_csv_to_parquet manual__2025-04-10T17:39:01.527746+00:00 [running]> on host f181186a1064
[2025-04-10T17:39:02.977+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='isoloops_ingest' AIRFLOW_CTX_TASK_ID='convert_csv_to_parquet' AIRFLOW_CTX_EXECUTION_DATE='2025-04-10T17:39:01.527746+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-10T17:39:01.527746+00:00'
[2025-04-10T17:39:02.980+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/isoloops_ingest.py", line 15, in csv_to_parquet
    df = pd.read_csv(CSV_PATH)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/sample_scope_songs.csv'
[2025-04-10T17:39:02.984+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=isoloops_ingest, task_id=convert_csv_to_parquet, execution_date=20250410T173901, start_date=20250410T173902, end_date=20250410T173902
[2025-04-10T17:39:02.988+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 92 for task convert_csv_to_parquet ([Errno 2] No such file or directory: 'data/sample_scope_songs.csv'; 72)
[2025-04-10T17:39:03.013+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-10T17:39:03.024+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
